"""update db for cc expire

Revision ID: 0390b377c214
Revises: ec80b5f850ef
Create Date: 2024-08-24 08:29:06.318063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0390b377c214'
down_revision = 'ec80b5f850ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'surname_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('surname_card', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
