import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime


"""
update db for invoice2

Revision ID: 0b9c78ed7013
Revises: 978991d126f0
Create Date: 2024-06-23 18:42:24.443752
"""

# Revision identifiers, used by Alembic.
revision = '0b9c78ed7013'
down_revision = '978991d126f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neurone_db', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_neurone_db_user_id'), 'neurone_db', ['user_id'], unique=False)
    op.create_foreign_key(None, 'neurone_db', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('neurone_entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('neurone_entries', sa.Column('created_on', AwareDateTime(), nullable=True))
    op.add_column('neurone_entries', sa.Column('updated_on', AwareDateTime(), nullable=True))
    op.create_index(op.f('ix_neurone_entries_user_id'), 'neurone_entries', ['user_id'], unique=False)
    op.create_foreign_key(None, 'neurone_entries', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'neurone_entries', type_='foreignkey')
    op.drop_index(op.f('ix_neurone_entries_user_id'), table_name='neurone_entries')
    op.drop_column('neurone_entries', 'updated_on')
    op.drop_column('neurone_entries', 'created_on')
    op.drop_column('neurone_entries', 'user_id')
    op.drop_constraint(None, 'neurone_db', type_='foreignkey')
    op.drop_index(op.f('ix_neurone_db_user_id'), table_name='neurone_db')
    op.drop_column('neurone_db', 'user_id')
    # ### end Alembic commands ###
