"""update db for Invoice data

Revision ID: 0c5119767475
Revises: 61d6cb0c5856
Create Date: 2024-08-19 19:04:10.259590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5119767475'
down_revision = '61d6cb0c5856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('company_name', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('city', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('state', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('zip', sa.String(length=16), nullable=True))
    op.add_column('purchases', sa.Column('country', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('vat_n', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('sdi', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('name_card', sa.String(length=256), nullable=True))
    op.add_column('purchases', sa.Column('surname_card', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'surname_card')
    op.drop_column('purchases', 'name_card')
    op.drop_column('purchases', 'sdi')
    op.drop_column('purchases', 'vat_n')
    op.drop_column('purchases', 'country')
    op.drop_column('purchases', 'zip')
    op.drop_column('purchases', 'state')
    op.drop_column('purchases', 'city')
    op.drop_column('purchases', 'address')
    op.drop_column('purchases', 'company_name')
    # ### end Alembic commands ###
