"""update db for reports

Revision ID: 3c81ba899c85
Revises: 88ac4eaa305e
Create Date: 2024-07-19 15:42:37.730374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c81ba899c85'
down_revision = '88ac4eaa305e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neurone_db', sa.Column('report1', sa.Text(), nullable=True))
    op.add_column('neurone_db', sa.Column('report2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neurone_db', 'report2')
    op.drop_column('neurone_db', 'report1')
    # ### end Alembic commands ###
