"""update db for v3.1

Revision ID: 88ac4eaa305e
Revises: a4952e83514d
Create Date: 2024-07-11 07:44:18.280395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ac4eaa305e'
down_revision = 'a4952e83514d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'last4',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
    op.alter_column('invoices', 'last4',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credits',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'last4',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('credit_cards', 'last4',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
