import sqlalchemy as sa

from alembic import op


"""
update db email verified

Revision ID: 978991d126f0
Revises: d1e2d89dab0f
Create Date: 2024-06-22 15:20:26.736471
"""

# Revision identifiers, used by Alembic.
revision = '978991d126f0'
down_revision = 'd1e2d89dab0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
