import sqlalchemy as sa

from alembic import op
import lib.util_sqlalchemy

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime


"""
update db for payments

Revision ID: d1e2d89dab0f
Revises: a34503944f4d
Create Date: 2024-06-16 20:36:47.242391
"""

# Revision identifiers, used by Alembic.
revision = 'd1e2d89dab0f'
down_revision = 'a34503944f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('cancelled_subscription_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    op.create_index(op.f('ix_users_company'), 'users', ['company'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_payment_id'), 'users', ['payment_id'], unique=False)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_payment_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_company'), table_name='users')
    op.drop_column('users', 'cancelled_subscription_on')
    op.drop_column('users', 'payment_id')
    # ### end Alembic commands ###
