"""update db for cc expire

Revision ID: ec80b5f850ef
Revises: 8074ade722fb
Create Date: 2024-08-23 17:27:57.922352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec80b5f850ef'
down_revision = '8074ade722fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'exp_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'exp_date',
               existing_type=sa.String(length=32),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
